services:
  ppiyong-api:
    image: ghcr.io/${ORG_NAME}/ppiyong-api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - my-network

  redis:
    image: redis:7.4.1
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my-network

volumes:
  redis_data:

networks:
  my-network:
    driver: bridge