spring:
  application:
    name: Back-end

  profiles:
    group:
      local: "local"
      dev: "dev"

  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  jwt:
    refresh:
      expiration: 604800 # 7일
    access:
      expiration: 86400 # 24시간
    secret: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs