spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true

  jwt:
    refresh:
      expiration: 604800 # 7일
    access:
      expiration: 86400 # 24시간
    secret: ${JWT_SECRET_KEY}

  data:
    redis:
      host: localhost
      port: 6379

  security:
    kakao:
      client-id: ${KAKAO_REST_API_KEY}
      redirect-uri: ${KAKAO_CALLBACK}

  map:
    kakao:
      api-key: ${KAKAO_MAP_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs